service: serverless-aws-dio
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamoDB:PutItem
            - dynamoDB:UpdateItem
            - dynamoDB:GetItem
            - dynamoDB:scan
          Resource: 
            - arn:aws:dynamodb:us-east-1:080955410482:table/ItemTableNew

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: fetchItems.handler
    events:
      - http:
          path: /items
          method: get
  fetchItem:
    handler: fetchItem.handler
    events:
      - http:
          path: /items/{id}
          method: get
  updateItem:
    handler: updateItem.handler
    events:
      - http:
          path: /items/{id}
          method: put      


resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
